version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - phishingPage:/data/db

  phishingPage:
    depends_on:
      - mongo
    image: aerosecgeek/ch-login-phishing-simulation
    ports:
      - 3000:3000

volumes:
  phishingPage:
